# Generated by Django 3.2 on 2025-06-07 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('group', models.CharField(default='worker', max_length=15)),
                ('address', models.TextField(blank=True, null=True)),
                ('phoneNumber', models.CharField(blank=True, max_length=20, null=True)),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='InitAgentsBalance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denar', models.FloatField(default=0)),
                ('dollar', models.FloatField(default=0)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Agents.agents')),
                ('yearId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Users.commercialyear')),
            ],
        ),
    ]
