# Generated by Django 3.2 on 2025-06-08 20:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_alter_users_privilege'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Agents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('length', models.FloatField(blank=True, null=True)),
                ('width', models.FloatField(blank=True, null=True)),
                ('thickness', models.FloatField(blank=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoiceDate', models.DateField()),
                ('currency', models.BooleanField(default=True)),
                ('invoiceNumber', models.CharField(blank=True, max_length=10, null=True)),
                ('dateAt', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.BooleanField(default=False)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Agents.agents')),
                ('userAuth', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('yearId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Users.commercialyear')),
            ],
        ),
    ]
