# Generated by Django 3.2 on 2025-06-08 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Agents', '0002_invoice_material'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('remain', models.FloatField()),
                ('unitCostPrice', models.FloatField()),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Agents.material')),
            ],
        ),
    ]
