# Generated by Django 3.2 on 2025-06-08 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_alter_users_privilege'),
        ('Agents', '0003_invoiceitems'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceitems',
            name='remain',
        ),
        migrations.CreateModel(
            name='InitMaterialQuantity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('currency', models.BooleanField(default=True)),
                ('unitCostPrice', models.FloatField()),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Agents.material')),
                ('yearId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Users.commercialyear')),
            ],
        ),
    ]
