# Generated by Django 3.2 on 2025-06-09 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Agents', '0004_auto_20250609_0033'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='invoiceNumber',
            new_name='invoiceCode',
        ),
    ]
