# Generated by Django 3.2 on 2025-06-09 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agents', '0006_auto_20250609_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitems',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='totalCost',
            field=models.FloatField(default=0),
        ),
    ]
