# Generated by Django 3.2 on 2025-06-20 14:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Users', '0002_alter_users_privilege'),
        ('Agents', '0007_auto_20250609_2148'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Withdraw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('withdrawDate', models.DateField()),
                ('currency', models.BooleanField(default=True)),
                ('totalCost', models.FloatField(default=0)),
                ('comments', models.TextField(blank=True, null=True)),
                ('dateAt', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.BooleanField(default=False)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Agents.destination')),
                ('userAuth', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('yearId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Users.commercialyear')),
            ],
        ),
        migrations.CreateModel(
            name='WithdrawItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('unitCostPrice', models.FloatField()),
                ('deleted', models.BooleanField(default=False)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Agents.material')),
                ('withdraw', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Agents.withdraw')),
            ],
        ),
    ]
