# Generated by Django 3.2 on 2025-06-20 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agents', '0008_destination_withdraw_withdrawitems'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='withdraw',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='withdraw',
            name='totalCost',
        ),
        migrations.AddField(
            model_name='withdrawitems',
            name='currency',
            field=models.BooleanField(default=True),
        ),
    ]
