# Generated by Django 3.2 on 2025-06-23 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Agents', '0010_agents_destination'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateAt', models.DateField()),
                ('workTime', models.FloatField()),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Agents.agents')),
            ],
        ),
    ]
