# Generated by Django 3.2 on 2025-06-24 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agents', '0011_attendes'),
    ]

    operations = [
        migrations.AddField(
            model_name='agents',
            name='salary',
            field=models.FloatField(default=0),
        ),
    ]
