# Generated by Django 3.2 on 2025-06-24 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agents', '0012_agents_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendes',
            name='workTime',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
