# Generated by Django 3.2 on 2025-07-01 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agents', '0013_alter_attendes_worktime'),
    ]

    operations = [
        migrations.AddField(
            model_name='agents',
            name='limitDenar',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='agents',
            name='limitDollar',
            field=models.FloatField(default=0),
        ),
    ]
