import { RouteInfo } from "./sidebar.metadata";
export const SideMenuRouts: RouteInfo[] = [
  // Admin Modules

  {
    path: "/pages/users/",
    title: "المستخدمين",
    iconType: "feather",
    icon: "users",
    class: "",
    groupTitle: false,
    badge: "",
    index: 7,
    badgeClass: "",
    role: ["admin"],
    submenu: [],
    selected: false,
  },

  //*********************************** */

  {
    path: "/acc/box/",
    title: " الحسابات",
    iconType: "feather",
    icon: "dollar-sign",
    class: "",
    index: 1,
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["accountant"],
    submenu: [],
    selected: false,
  },

  {
    path: "/acc/agents/",
    title: " العملاء",
    iconType: "feather", /// 'feather',
    icon: "users",
    class: "",
    index: 2,
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["accountant"],
    submenu: [],
    selected: false,
  },
  {
    path: "/acc/mnforder/",
    title: " طلبات التصنيع",
    iconType:   'feather',
    icon: "tool",
    class: "",
    index: 2.5,
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["accountant"],
    submenu: [],
    selected: false,
  },
  {
    path: "/acc/store/",
    title: " المخزن",
    iconType:  'feather',
    icon: "archive",
    class: "",
    index: 3,
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["accountant"],
    submenu: [],
    selected: false,
  },

  {
    path: "/acc/invoice/",
    title: " شراء مواد",
    iconType:  'feather',
    icon: "shopping-cart",
    class: "",
    index: 5,
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["accountant"],
    submenu: [],
    selected: false,
  },
  {
    path: "/acc/withdraw/",
    title: " سحب مواد مخزنية",
    iconType:  'feather',
    icon: "corner-up-right",
    class: "",
    index: 4,
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["accountant"],
    submenu: [],
    selected: false,
  },
  {
    path: "/acc/attend/",
    title: "حضور العمال",
    iconType: 'feather',
    icon: "check-circle",
    class: "",
    index: 4,
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["accountant"],
    submenu: [],
    selected: false,
  },
  

  {
    path: "/acc/category/",
    title: "تبويب المصارف",
    iconType:  'feather',
    icon: "align-justify",
    class: "",
    index: 11,
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["accountant"],
    submenu: [],
    selected: false,
  },

  {
    path: "/drw/design/",
    title: " رسم الطلبات",
    iconType:  'feather',
    icon: "cpu",
    class: "",
    index: 11,
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["drawing"],
    submenu: [],
    selected: false,
  },

  {
    path: "/cnc/page/",
    title: "CNC طلبات ",
    iconType:  'feather',
    icon: "cpu",
    class: "",
    index: 11,
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["cnc"],
    submenu: [],
    selected: false,
  },
    
  {
    path: "/plasma/page/",
    title: "طلبات البلازما",
    iconType:  'feather',
    icon: "bi bi-diagram-3 sidebarIcon sidebarIconColor",
    class: "",
    index: 11,
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["plasma"],
    submenu: [],
    selected: false,
  },

  {
    path: "/cutting/page/",
    title: "طلبات القص",
    iconType:  'feather',
    icon: "bi bi-diagram-3 sidebarIcon sidebarIconColor",
    class: "",
    index: 11,
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["cutting"],
    submenu: [],
    selected: false,
  },

  {
    path: "/bending/page/",
    title: "طلبات العواجة",
    iconType:  'feather',
    icon: "cpu",
    class: "",
    index: 11,
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["bending"],
    submenu: [],
    selected: false,
  },
];
