# Generated by Django 3.2 on 2025-06-08 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Box', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boxtransaction',
            name='fromOther',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='boxtransaction',
            name='toOther',
            field=models.BooleanField(default=True),
        ),
    ]
