# Generated by Django 3.2 on 2025-06-10 17:04

import Apps.Box.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Agents', '0007_auto_20250609_2148'),
        ('Users', '0002_alter_users_privilege'),
        ('Box', '0002_auto_20250608_1648'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManufacturingOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateAt', models.DateTimeField(auto_now_add=True)),
                ('currency', models.BooleanField(default=True)),
                ('price', models.FloatField()),
                ('comments', models.TextField(blank=True, null=True)),
                ('done', models.BooleanField(default=False)),
                ('deleted', models.BooleanField(default=False)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Agents.agents')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Users.users')),
                ('yearId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Users.commercialyear')),
            ],
        ),
        migrations.CreateModel(
            name='ManufacturingPath',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(max_length=15)),
                ('index', models.IntegerField()),
                ('doneAt', models.DateTimeField(blank=True, null=True)),
                ('done', models.BooleanField(default=False)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Box.manufacturingorder')),
                ('userDoneId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Users.users')),
            ],
        ),
        migrations.CreateModel(
            name='ManufacturingImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=Apps.Box.models.get_document_upload_path)),
                ('deleted', models.BooleanField(default=False)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Box.manufacturingorder')),
            ],
        ),
        migrations.CreateModel(
            name='ManufacturingFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=Apps.Box.models.get_document_upload_path)),
                ('deleted', models.BooleanField(default=False)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Box.manufacturingorder')),
            ],
        ),
    ]
