# Generated by Django 3.2 on 2025-06-10 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Box', '0003_manufacturingfiles_manufacturingimages_manufacturingorder_manufacturingpath'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturingpath',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
