# Generated by Django 3.2 on 2025-06-11 14:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Box', '0004_manufacturingpath_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manufacturingorder',
            name='userId',
        ),
        migrations.AddField(
            model_name='manufacturingorder',
            name='userAuth',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='manufacturingpath',
            name='userDoneId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
