# Generated by Django 3.2 on 2025-06-13 19:51

import Apps.Box.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Box', '0005_auto_20250611_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturingorder',
            name='designFile',
            field=models.FileField(blank=True, null=True, upload_to=Apps.Box.models.get_document_upload_path),
        ),
        migrations.DeleteModel(
            name='ManufacturingFiles',
        ),
    ]
