# Generated by Django 3.2 on 2025-06-13 21:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Box', '0007_remove_manufacturingpath_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturingpath',
            name='userDoneId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
