# Generated by Django 3.2 on 2025-06-21 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Box', '0008_alter_manufacturingpath_userdoneid'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturingorder',
            name='otherOrder',
            field=models.BooleanField(default=False),
        ),
    ]
