# Generated by Django 3.2 on 2025-06-22 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Box', '0009_manufacturingorder_otherorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturingorder',
            name='otherPrice',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='ManufacturingItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('quantity', models.FloatField(default=0)),
                ('unitCostPrice', models.FloatField(default=0)),
                ('width', models.FloatField(blank=True, null=True)),
                ('length', models.FloatField(blank=True, null=True)),
                ('thickness', models.FloatField(blank=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Box.manufacturingorder')),
            ],
        ),
    ]
