# Generated by Django 3.2 on 2025-06-28 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Agents', '0013_alter_attendes_worktime'),
        ('Box', '0011_boxtransaction_destination'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manufacturingorder',
            name='otherOrder',
        ),
        migrations.AddField(
            model_name='manufacturingorder',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Agents.destination'),
        ),
    ]
