# Generated by Django 3.2 on 2025-06-07 08:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommercialYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoneNumber', models.TextField(blank=True, default='', max_length=30)),
                ('img', models.ImageField(blank=True, null=True, upload_to='users')),
                ('privilege', models.CharField(choices=[('admin', 'admin'), ('partner', 'partner'), ('accountant', 'accountant')], default='store', max_length=25)),
                ('deleted', models.BooleanField(default=False)),
                ('permission', models.IntegerField(blank=True, default=1, null=True)),
                ('auth', models.OneToOneField(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='for_auth_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
