# Generated by Django 3.2 on 2025-06-08 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='privilege',
            field=models.CharField(choices=[('admin', 'admin'), ('accountant', 'accountant'), ('drawing', 'drawing'), ('cutting', 'cutting'), ('bending', 'bending'), ('cnc', 'cnc'), ('plasma', 'plasma')], default='store', max_length=25),
        ),
    ]
